server:
  port: 8002
  enable-self-preservation: false

#设置服务的名称
spring:
  application:
    name: eureka_jade_a

#往eureka_service端注册的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka