server:
  port: 8002
  enable-self-preservation: false

#设置服务的名称
spring:
  application:
    name: eureka_jade_a

#往eureka_service端注册的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
  instance:
    # 每间隔1s，向服务端发送一次心跳，证明自己依然“存活”
    lease-renewal-interval-in-seconds: 1
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2