spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  druid:
    type: com.alibaba.druid.pool.DruidDataSource
    druidClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    #最大连接数
    maxActive: 30
    #最小连接数
    minIdle: 5
    #获取连接的最大等待时间
    maxWait: 10000
    #解决mysql8小时的问题
    validationgQuery: SELECT 'X'
    #空闲连接的检查时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #空闲连接最小空闲时间
    minEvictableIdleTimeMillis: 300000
    #配置监控统计拦截的filters,去掉后监控界面sql将无法统计
    filters: stat
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
      # 缓存配置读取
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

# ext config
domain:
  name: www.jade.com:9090

#spring.profiles.active=prd
server:
  port: 9090

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
#    com.threefivework.mymall.dao.mapper: DEBUG #包路径为mapper文件包路径
logging:
  level:
    org.springframework.web: TRACE